### ISSUE TITLE
Is this compatible with Node 4.1+? 

### ISSUE THREAD

**Issue by darshit-shah** [smremde/node-lp_solve#13] opened 2015-11-09 10:00 UTC
I upgrade my node version from 0.8.17 to 4.1 and now lo_solve stopped working.
I tried to do fresh npm install but still failed.
Do I suppose to do any other step?

**Comment by smremde** [comment] 2015-11-09 17:57
I haven't tried Node 4.1. What is the error?

**Comment by darshit-shah** [comment] 2015-11-10 08:27
d:\{{some_folder}}\node_modules\lp_solve\node_modules\bindings\bindings.
js:83
        throw e
              ^
Error: The specified procedure could not be found.
d:\{{some_folder}}\node_modules\lp_solve\build\Release\lp_solve.node
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at bindings (d:\{{some_folder}}\node_modules\lp_solve\node_modules\b
indings\bindings.js:76:44)
    at Object.<anonymous> (d:\{{some_folder}}\node_modules\lp_solve\inde
x.js:4:35)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)

**Comment by smremde** [comment] 2015-11-10 09:30
No error when you install the pakage?

**Comment by darshit-shah** [comment] 2015-11-10 09:31
No

**Comment by smremde** [comment] 2015-11-10 09:41
Yes there is. I just tested.

It is related to this issue:

https://github.com/nodejs/node/issues/2798

I don't intend on fixing this as a priority, it require migrating to NAN2. There are some scripts to migrate code automatically which I might give a quick try.

**Comment by darshit-shah** [comment] 2015-11-10 10:04
Thank you.

-----Original Message-----

**Comment by MrOrz** [comment] 2016-06-10 08:41
I can install node-lp_solve using node 4.4.5 with no issue.

However, the installation fails on node 6.2.1.

Seems that `node_modules/nan/nan.h:590:20` is the cause>

```
> lp_solve@0.2.12 install /Users/mrorz/workspace/gis-inner/node_modules/lp_solve
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CC(target) Release/obj.target/lp_solve_5.5/deps/lp_solve/lp_solve_5.5/lp_MDO.o
  CC(target) Release/obj.target/lp_solve_5.5/deps/lp_solve/lp_solve_5.5/shared/commonlib.o

  -- (irrelevant warnings omitted) --

  CC(target) Release/obj.target/lp_solve_5.5/deps/lp_solve/lp_solve_5.5/yacc_read.o
  LIBTOOL-STATIC Release/lp_solve_5.5.a
  CXX(target) Release/obj.target/lp_solve/lp_solve.o
In file included from ../lp_solve.cc:2:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../lp_solve.cc:352:7: warning: unused variable 'res' [-Wunused-variable]
                int res = solve(lp);
                    ^
../lp_solve.cc:2807:2: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you
      mean 'delete[]'? [-Wmismatched-new-delete]
        delete var;
        ^
              []
../lp_solve.cc:2803:14: note: allocated with 'new[]' here
        REAL* var = new REAL[var_n];
                    ^
2 warnings and 4 errors generated.
make: *** [Release/obj.target/lp_solve/lp_solve.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mrorz/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Users/mrorz/.nvm/versions/node/v6.2.1/bin/node" "/Users/mrorz/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mrorz/workspace/gis-inner/node_modules/lp_solve
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

**Comment by smremde** [comment] 2018-12-19 09:56
Closing this nan has been updated. 

If it's still a problem, reopen. I'm using version 8.9.4 no problem.

**Closed by smremde** 2018-12-19 09:56 UTC
